# Generated by Django 5.1 on 2024-09-06 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='major',
        ),
        migrations.AlterField(
            model_name='professorprofile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.department'),
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.course', to_field='course_code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile', to_field='user')),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
